version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: umbrel-podping-alpha-app_web_1
      APP_PORT: 8089

  web:
    image: ericpp/gossip-listener@sha256:f8c44bf200dd0e8d23c57c2c5d7ac92b3dc13f45e086850396a6b6e36128e225
    entrypoint: ["/data/init.sh"]
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    volumes:
      - ${APP_DATA_DIR}/data:/data
