version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: umbrel-podping-alpha-app_web_1
      APP_PORT: 8089

  web:
    image: ericpp/podping-gossipwatcher@sha256:3822da339a870bc428f06c5aa9c53177b5b34c202ab99e504da08e744712f546
    init: true
    working_dir: /data
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      NODE_FRIENDLY_NAME: "${APP_NODE_FRIENDLY_NAME}"
      SSE_ENABLED: "1"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
