version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: umbrel-podping-alpha-app_web_1
      APP_PORT: 8089

  web:
    image: ericpp/podping-gossipwatcher:latest@sha256:5b832bdd0dc166fd2bf2b157bb3a6b9fb3ad1c4dc1b4baec6c5d29a0f85a4a80
    init: true
    working_dir: /data
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      NODE_FRIENDLY_NAME: "${APP_NODE_FRIENDLY_NAME}"
      SSE_ENABLED: "1"
